blank_issues_enabled: true
contact_links:
  - name: EasySkipList Discussions
    url: https://github.com/MHKarami97/EasySkipList/discussions
    about: For other types of questions, consider using Discussions.
  - name: Issue Management Policies
    url: https://github.com/MHKarami97/EasySkipList/blob/main/IssueManagementPolicies.md
    about: More information on our issue management policies is available here.
